# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest]
        python-version: ["3.5"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test with pytest
      run: |
        python -m unittest discover -s pyHW//tests -t pyHW/tests
    - name: Build executable
      run: |
        python -m PyInstaller --noconsole --onefile pyHW/app.spec
    - uses: actions/upload-artifact@v3
      with:
          name: app-binary
          path: pyHW/dist/app.exe